# Generated by Django 5.2.8 on 2025-11-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholereport',
            name='region',
            field=models.CharField(choices=[('Greater Accra', 'Greater Accra'), ('Ashanti', 'Ashanti'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Western North', 'Western North'), ('Central', 'Central'), ('Volta', 'Volta'), ('Oti', 'Oti'), ('Northern', 'Northern'), ('Savannah', 'Savannah'), ('North East', 'North East'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Ahafo', 'Ahafo')], default='Greater Accra', max_length=50),
        ),
    ]
