# Generated by Django 5.2.8 on 2025-11-14 01:21

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_user_delete_otplog_userprofile_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptionrequest',
            name='reference',
            field=models.CharField(default=core.utils.generate_reference, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='core_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='core_users_permissions', to='auth.permission'),
        ),
    ]
